// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectMVC.Models;

namespace ProjectMVC.Migrations.Buyer
{
    [DbContext(typeof(BuyerContext))]
    [Migration("20200201091436_SendCreate")]
    partial class SendCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectMVC.Models.Buyer", b =>
                {
                    b.Property<int>("Bid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Baddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bpassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Phoneno")
                        .HasColumnType("int");

                    b.HasKey("Bid");

                    b.ToTable("Buyers");
                });
#pragma warning restore 612, 618
        }
    }
}
